# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
	PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# Find if we have color prompt
# Uncomment to force color prompt
#force_color_prompt=yes
case "$TERM" in
	xterm-color|*-256color) color_prompt=yes ;;
esac

if [ -n "$force_color_prompt" ]; then
	if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
		# We have color support
		color_prompt=yes
	else
		color_prompt=
	fi
fi

# Git branch in command line
find_branch () {
	_branch="$(git branch 2>/dev/null | sed -e "/^\s/d" -e "s/^\*\s//")"
	[ ! -z $_branch ] && printf " - %s" $_branch
}

if [ "$color_prompt" = yes ]; then
	PS1="[\[\033[01m\]\u@\h\[\033[00m\] \W\$(find_branch)]\$ "

	# Color out some more stuff
	alias grep='grep --color=auto'
	alias fgrep='fgrep --color=auto'
	alias egrep='egrep --color=auto'
	alias diff='diff --color=auto'
	alias ip='ip --color=auto'
else
	PS1="[\u@\h \W\$(find_branch)]\$ "
fi

# Some ls aliases
alias lla='ls -lahF --group-directories-first'
alias ll='ls -lABhF --group-directories-first'
alias la='ls -ABhF'
alias l='ls -lBhF --group-directories-first'

# Create a new directory and cd into it
new() {
	mkdir "$1" && cd "$1"
}

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
	for rc in ~/.bashrc.d/*; do
		if [ -f "$rc" ]; then
			. "$rc"
		fi
	done
fi
